language: node_js
node_js:
- lts/*
install:
- yarn install
script:
- yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
  - secure: M+di66L9FvXQuNiBKIbvPeVFTq2mMb4erlNiNJWAmWqjJYWofh0eIGU6mOU44CN3ef7HL1z113D17OAFAVCgONEUtHlcPAYmbnerKTm8S6slUgthemSEoIp6NjRzwyCi1RzBg2WqP/2ZwhtNOmTuwIQ4qvX5GuWLUktgVn2P026eG3lp1do2Pu8OksmfHUbQA0eHZMZUbH3F+GJ2u8w6jfRSLohIMfhW8NXBiDF6qjS6yj8xX/EnpcOcNbcld/jn+CIvp6vpwAt08VqOHEsict/F6eSQ95arQAM8yU/B58vbhNoD7B00cakGJXY1dgkGExy58o4hYWwVDuUEpuiKJAmW1NNuf0O1CK/LyE1rFJCfw246Ei4WcbYoVkvYwvKy/m/RNQNE73OazueG9KKBUkGbi3pxiD6D+5sRa2g+PPhWDL0l8kEuUny9f4yu3Ff5JieA9X0xXjO+PvqPsYHK3CDQAPd6qqOBiTBuO0/iM2VE6+CgOEo37tQW9GvebnhoozdCckgpFlWG2FVP+LLap3pL+h6kcd86DRthYMkM6uKzcm8PyqKA2ZJ4iIV9G2ub12U4IxCJEKIEmcYFQZm9nC1G4TcwLOkZ2cqOqJGTKbUZJoYVhWbAdtGI3f9Gt6+W1zO2GMjivg2FTLtNvSrc1gFSHNuwxkQfxsGLydmAD44=
